#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 16 16:13:53 2020

@author: samarth
"""
import numpy as np
mean = [0, 0]
cov = [[0.001, 0], [0, 0.001]]  # diagonal covariance

import matplotlib.pyplot as plt
# x, y = np.random.multivariate_normal(mean, cov, 200).T
# plt.plot(x, y, 'x')
# plt.axis('equal')
# plt.show()


from workspace import Workspace
w=Workspace()
for i in range (6):
    plt.plot(w.landmark_x[i,:], w.landmark_y[i,:], 'x')
    